config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'
resources :password_resets

  resources :items

  resources :controllers

  get 'sessions/new'

  get 'users/new'
get "logout" => "sessions#destroy", :as => "logout"
get "login" => "sessions#new", :as => "login"
get "signup" => "users#new", :as => "signup"
resources :users
resources :sessions

   root 'sessions#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
 
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
	#attr_accessor :email, :password, :remember_me
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	def not_authenticated
	redirect_to login_url, :alert => "First login to access this page."
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/controllers/password_resets_controller.rb
# app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  user = login(params[:email], params[:password], params[:remember_me])
  if user
    redirect_to items_path, :notice => "Logged in!"
  else
    flash.now.alert = "Email or password was invalid"
    render :new
  end
end

def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
  	UserMailer.welcome_email(@user).deliver_now
    redirect_to root_url, :notice => "Signed up!"
  else
    render :new
  end
end
private
def user_params
      params.require(:user).permit(:email,:password)

end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorcery App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container-fluid" style="background-color:#d3d3d3;postion:fixed">
  <h1 class="text-center">Welcome TO <strong>NYROS TECHNOLOGIES</strong></h1>
</header>
<div class="navbar-header  col-lg-offset-1 ac">
      <a class="navbar-toggle btn " data-toggle="collapse" 
         data-target="#example-navbar-collapse"><span class="glyphicon glyphicon-align-justify"></span></a>
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%=image_tag("icon.png" ,:alt => "home image" ,:width => 100,:style=>"margin-top:-7px;") %></a>
</div>
<div class="collapse navbar-collapse ac"  id="example-navbar-collapse">
    <ul class="nav navbar-nav ">
        <%temp = items_path if current_user%>
        <%temp = login_path if !current_user%>
        <li class="active"> <%= link_to 'Items',temp , class:'btn'%></li>
   </ul>     
    <ul class="nav navbar-nav pull-right ">
        <% if current_user %>
        <li style='margin-top:17px;color:white'>Logged in as <strong><%= current_user.email %></strong>.</li>
        <li><%= link_to "Log out", logout_path , :class => 'btn' %></li>
        <% else %>
        <li><%= link_to "Sign up", signup_path, :class => 'btn '  %></li>
        <li><%= link_to "Login", login_path, :class => 'btn '  %></li>
        <li><%= link_to 'Forgot Password?', new_password_reset_path %></li>
        <% end %>
    </ul>
</div>

<% if notice %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>

<br><br><br>
<footer class="container-fluid" style="background-color:#d3d3d3;padding-top:10px;width:100%;position:fixed;bottom:0;left:0;">
  <p class="text-center">Copyright © 2015 -SreeRaj</p>
</footer>
</body>
</html>
 

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/users/index.html.erb
<p>HAII</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>

    <div id="error_explanation " class="alert alert-danger overlay" >
      <h5 class="text-center">Form is invalid</h5>
      <ul class="col-xs-offset-1 col-md-offset-5">
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </p>
    </div>
    <br><br><br><br><br><br>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email ,class:'form-control'%>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password ,class:'form-control'%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation ,class:'form-control'%>
  </div>
  <br>
  <%= f.submit class:'btn btn-info btn-block' %>
<% end %>  